### ISSUE TITLE
error planning & importing argocd_application

### ISSUE THREAD

**Issue by beyondbill** [oboukili/terraform-provider-argocd#251] opened 2023-04-07 01:34 UTC
I'm upgrading argocd provider from v2.2 to v5.0.1. There were already `argocd_application`s created in the state file on provider v2.2. After upgrading to v5.0.1, the provider crashed during planning due to some of the `argocd_application`s had unsupported attribute `ksonnet` in the schema, although `ksonnet` has never been set anywhere in the "*.tf" HCL files.

```
2023-04-06T22:14:24.564Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: attribute no longer present in schema: @module=sdk.helper_schema attribute=ksonnet tf_resource_type=argocd_application tf_rpc=UpgradeResourceState tf_provider_addr=registry.terraform.io/oboukili/argocd tf_req_id=d8058092-8cac-cacd-2ee6-4dc3ac36ee53 @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:500 timestamp=2023-04-06T22:14:24.562Z

2023-04-06T22:14:24.732Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: attribute no longer present in schema: @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:500 tf_provider_addr=registry.terraform.io/oboukili/argocd tf_req_id=9461d174-f16f-2afd-229b-aa04adc7b088 tf_resource_type=argocd_application tf_rpc=UpgradeResourceState @module=sdk.helper_schema attribute=ksonnet timestamp=2023-04-06T22:14:24.732Z

2023-04-06T22:14:24.756Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: attribute no longer present in schema: tf_resource_type=argocd_application attribute=ksonnet @module=sdk.helper_schema tf_provider_addr=registry.terraform.io/oboukili/argocd tf_req_id=2b510c39-5460-3a23-eaae-372d3adf1869 tf_rpc=UpgradeResourceState @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:500 timestamp=2023-04-06T22:14:24.756Z

2023-04-06T22:14:24.767Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/oboukili/argocd/5.0.1/linux_amd64/terraform-provider-argocd_v5.0.1 pid=53350 error="exit status 2"
```

I went ahead and removed all the `argocd_application`s from Terraform state. The `terraform plan` ran successfully with no more argocd provider crash. But when I tried to import the `argocd_application`s back, some can be successfully imported but the others show the very similar error. I did not enable debug-level logs this time but they should be the same.

<img width="940" alt="Screenshot 2023-04-06 at 9 21 08 PM" src="https://user-images.githubusercontent.com/10553863/230521371-4b697cdf-712d-4f65-aaf0-9a7f4242b3c9.png">

The most frustrating part is that there's no difference (except app names, source paths and helm values) among the `argocd_application`s (at least not on the Terraform code level). Yet some of them show the issue but the others do not.

**Comment by onematchfox** [comment] 2023-04-07 10:06
Hi @beyondbill,

> when I tried to import the argocd_applications back, some can be successfully imported but the others show the very similar error.

I'm not sure I completely follow you here. The initial error you mention relates to issues when upgrading the schema of the resource due to the removal of support for `ksonnet`. However, the error in your screenshot when importing is an RPC error `code = Unavailable desc = transport is closing`. These don't seem like similar issues to me. Am I missing something?

That said, the RPC error is going to be a tricky one to try and debug if we can't reliably reproduce it. Have you retried importing resources, and can you confirm that this happens consistently on any given application? Also, there are some pointers on this specific issue [here](https://github.com/grpc/grpc-go/#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing). If you can provide logs from both client and server (and potentially any proxy/LB in between - depending on how you have exposed the ArgoCD server), then this might help.

**Comment by beyondbill** [comment] 2023-04-07 17:57
@onematchfox Thanks for the quick response! Sorry I forgot to post the initial error during planning! It was 

```
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
```

which was very similar to the error later encountered during importing. I only enabled DEBUG level logging during planning but not importing. Based on the DEBUG logs which I've included in my original post, the argocd provider crashed due to a goroutine panic. So this is more like a client side issue to me.

Would it be helpful if I enable DEBUG level logging during importing? I can always reproduce the issue when importing two specific applications, though their config seems no different than others, which have been successfully planned / imported. I can also monitor server side logs. You meant the argocd server (vs. repo server, etc) specifically, right?

**Comment by onematchfox** [comment] 2023-04-09 10:46
> Based on the DEBUG logs which I've included in my original post, the argocd provider crashed due to a goroutine panic. So this is more like a client side issue to me.

I'm not 100% sure here but I think the log lines you are referring too are actually expected as the underlying schema needed to be upgraded across the major versions. I.e. these are not _error_ messages but rather simply _debug_ level messages.

> Would it be helpful if I enable DEBUG level logging during importing? I can always reproduce the issue when importing two specific applications, though their config seems no different than others, which have been successfully planned / imported. I can also monitor server side logs. You meant the argocd server (vs. repo server, etc) specifically, right?

Yes, please. Although we need the [GRPC log messages](https://github.com/grpc/grpc-go/#how-to-turn-on-logging) (from both client and argocd server). 

Also... if you are able to reliably reproduce this I'm wondering if there might be something else at play here. I seem to remember seeing something online about this being potentially related to differences in the protobuf definition between client and server. Can you confirm what version of ArgoCD you are running? If this is <2.4 then the best and first course of action will be to upgrade ArgoCD.

**Comment by beyondbill** [comment] 2023-04-09 18:25
> the argocd provider crashed due to a goroutine panic.

Here's what I referred to. Sorry again, I forgot to attach the goroutine panic error logs to the original post
```
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1:
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: goroutine 12 [running]:
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0xc000b49680, {0xc000469420, 0x7, 0x7}, {0x1ef8060, 0xc000b497d0}, 0xc000514140)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:327 +0x959
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc000469420, 0x7, 0x7}, {0x1ef8060, 0xc000b497d0})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:107 +0x14c
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc0002e87e0?, {0xc0002e87e0?, 0x6, 0x6}, {0x202ff20, 0xc000c83d40})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:222 +0x312
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc0002e87e0, 0x6, 0x6}, {0x202ff20, 0xc000c83d40})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:109 +0x11c
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:122
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc000b49680, {0xc000317220?, 0x5, 0x5}, {0x1ef8060, 0xc000b497e8})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:142 +0x52a
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc000317220, 0x5, 0x5}, {0x1ef8060, 0xc000b497e8})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:103 +0xa5
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc000d44280?, {0xc000d44280?, 0x4, 0x4}, {0x202ff20, 0xc000c83cb0})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:222 +0x312
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc000d44280, 0x4, 0x4}, {0x202ff20, 0xc000c83cb0})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:109 +0x11c
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:122
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc000b49680, {0xc000c83da0?, 0x3, 0x3}, {0x1ef8060, 0xc000b49800})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:142 +0x52a
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc000c83da0, 0x3, 0x3}, {0x1ef8060, 0xc000b49800})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:103 +0xa5
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc0004ab620?, {0xc0004ab620?, 0x2, 0x2}, {0x202ff20, 0xc000c83bf0})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:222 +0x312
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc0004ab620, 0x2, 0x2}, {0x202ff20, 0xc000c83bf0})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:109 +0x11c
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:122
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc000b49680, {0xc000d42610?, 0x1, 0x1}, {0x1ef8060, 0xc000b49818})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:142 +0x52a
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc000b49680, {0xc000d42610, 0x1, 0x1}, {0x1ef8060, 0xc000b49818})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:103 +0xa5
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc000b49680, {0xc000d42610, 0x1, 0x1}, {0x1ef8060, 0xc000b49818})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:89 +0x3f9
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0004fb300, {0x23680ba, 0x4}, {0x1ef8060, 0xc000b49818})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:227 +0x210
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/oboukili/terraform-provider-argocd/argocd.flattenApplication(0xc00049b000, 0x273f5c8?)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:411 +0x189
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDApplicationRead({0x273f5c8, 0xc0004accc0}, 0xc0004fb300, {0x2196a80?, 0xc000298300})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_application.go:288 +0x419
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0006ee1c0, {0x273f600, 0xc000618ae0}, 0xd?, {0x2196a80, 0xc000298300})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0006ee1c0, {0x273f600, 0xc000618ae0}, 0xc00057fc70, {0x2196a80, 0xc000298300})
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0004bfa88, {0x273f600?, 0xc0006189c0?}, 0xc000382440)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00024ba40, {0x273f600?, 0xc0006181b0?}, 0xc0004ac300)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x226c460?, 0xc00024ba40}, {0x273f600, 0xc0006181b0}, 0xc000242000, 0x0)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004c81e0, {0x27475e0, 0xc00022c4e0}, 0xc00080e000, 0xc00070d3b0, 0x39ac0d0, 0x0)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: google.golang.org/grpc.(*Server).handleStream(0xc0004c81e0, {0x27475e0, 0xc00022c4e0}, 0xc00080e000, 0x0)
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-04-06T22:14:24.765Z [DEBUG] plugin.terraform-provider-argocd_v5.0.1: 	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
2023-04-06T22:14:24.767Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/oboukili/argocd/5.0.1/linux_amd64/terraform-provider-argocd_v5.0.1 pid=53350 error="exit status 2"
```

> Can you confirm what version of ArgoCD you are running? If this is <2.4 then the best and first course of action will be to upgrade ArgoCD.

2.3.4. We are going to upgrade argocd server to 2.5.5 in the next couple of months. Maybe I should re-visit this issue after that before investing more time now.

@onematchfox Feel free to close this issue for now unless you see something obvious in the panic logs above. Thanks again!

**Comment by onematchfox** [comment] 2023-04-11 06:58
Hi @beyondbill,

> Feel free to close this issue for now unless you see something obvious in the panic logs above.

Sorry, I don't see anything within the provided logs that would indicate the cause of the RPC error.

> 2.3.4. We are going to upgrade argocd server to 2.5.5 in the next couple of months. Maybe I should re-visit this issue after that before investing more time now.

`2.3.4` is recent enough that I would be surprised if there are issues in compatibility with the protobufs. But regardless, it is no longer supported. So, please do feel free to reach out again if the issue persists once you have upgraded.

Cheers!

**Closed by onematchfox** 2023-04-11 06:58 UTC
