### ISSUE TITLE
Missing "project" field in argocd_repository resource.

### ISSUE THREAD

**Issue by VladoPortos** [oboukili/terraform-provider-argocd#215] opened 2022-11-05 08:07 UTC
Hello,
I think there is missing field in resource "argocd_repository", and that's for "project" it is in ArgoCD and I would assume the same needs to be in the resource. Or what is the correct way to create a repository and assign it to an already existing project ?

**Comment by onematchfox** [comment] 2022-11-08 06:45
Hi @VladoPortos, You are quite correct - this is currently not possible with the provider. It should howevere be fairly easy to implement if you want to give it a shot? For inspiration/reference, you can look at how `project` has been implemented on `argocd_cluster`.

**Comment by VladoPortos** [comment] 2022-11-08 07:20
Hi @onematchfox, I would love to, but I do not know GO well enough to be confident doing changes to module that can affect production systems etc... I'm more of a python coder :) for now I'm going to solve it by using the ArgoCD API call.

**Comment by onematchfox** [comment] 2022-11-28 07:16
Duplicate of #183

**Closed by onematchfox** 2022-11-28 07:16 UTC
Labels: duplicate, enhancement
