### ISSUE TITLE
Creation of an AnpplicationSet

### ISSUE THREAD

**Issue by HaukeMarquardt** [oboukili/terraform-provider-argocd#103] opened 2021-10-05 07:11 UTC
Hi,
is it possible to create an ApplicationSet with this provider? 
(https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/)

I can't find anything about it in the documentation.
If not, is this feature on the roadmap?

Thanks.

**Comment by oboukili** [comment] 2021-10-05 07:18
Hello, unfortunately it is not possible, duplicate of #88.

**Closed by oboukili** 2021-10-05 07:18 UTC

**Comment by oboukili** [comment] 2021-10-05 07:21
WIth that being said, you can achieve the same feature with Terraform `dynamic` blocks and the `argocd_application` resource. The applicationSet controller simply allows for templating ArgoCD applications.

**Comment by HaukeMarquardt** [comment] 2021-10-05 07:55
Ok, thanks for the quick answer.

The git-generator for ApplicationSets makes it possible to create apps just by commiting to a repository, which is exactly the functionality I want to achive.
I think I should use a provider to create the custom resource for the ApplicationSet with terraform.

Thank you for pointing this out.

**Comment by alekc** [comment] 2021-10-12 09:34
@HaukeMarquardt for that,  the https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest can be used as a fallback as well.

**Comment by yurok15** [comment] 2022-12-26 05:55
@alekc Unfortunately you can't use manifest. If you change manifest terraform destroy it and create it again. All other applications will be recreated as well and all containers will be also re-created

**Comment by alekc** [comment] 2022-12-26 09:25
@yurok15 a lot of time has passed from 2021 :) . 

Not sure about the behaviour of the official kubernetes provider, what I am using at the moment is my fork of kubectl provider (https://registry.terraform.io/providers/alekc/kubectl/latest/docs) and it behaves pretty well for this. 

I.e. see https://registry.terraform.io/modules/alekc/argocd/application/latest especially https://github.com/alekc/terraform-application-argocd/blob/4477ade34f13b6623a51bfa0fb606d1d5202348e/main.tf#L59
